---
apiVersion: v1
kind: Pod
metadata:
  name: simplewebapp
  labels:
    type: webserver
spec:
  containers:
  - name: web
    image: systemdevformations/simple-webapp
    ports:
    - containerPort: 5000